name: build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main
          
        - name: Setting Up
          run: |
            sudo apt-get install apksigner
            
        - name: build overlay
          run: |
            sudo chmod a+x -R bin/*
            sudo bash build.sh "all"

        - name: check
          run: |
            ls -alh "output"
            
        - name: upload artifact
          uses: actions/upload-artifact@main
          with:
            name: overlay
            path: output/*
